services:
  - type: web
    name: stock-bot-orchestrator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY

  - type: web
    name: stock-bot-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run chatbot.py --server.port $PORT --server.enableCORS false
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY

  - type: web
    name: stock-bot-forecast
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run forecast.py --server.port $PORT --server.enableCORS false
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
